# Generated by Django 2.1.7 on 2019-03-16 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='age',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ethnicity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ethnicity', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='polideology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('politicalideology', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='politics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('politics', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='religion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('religion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='usregion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usregion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='usstates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usstate', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='profile_locked',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.age'),
        ),
        migrations.AddField(
            model_name='user',
            name='education',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.education'),
        ),
        migrations.AddField(
            model_name='user',
            name='ethnicity',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.ethnicity'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.gender'),
        ),
        migrations.AddField(
            model_name='user',
            name='income',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.income'),
        ),
        migrations.AddField(
            model_name='user',
            name='politicalideology',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.polideology'),
        ),
        migrations.AddField(
            model_name='user',
            name='politics',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.politics'),
        ),
        migrations.AddField(
            model_name='user',
            name='race',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.race'),
        ),
        migrations.AddField(
            model_name='user',
            name='religion',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.religion'),
        ),
        migrations.AddField(
            model_name='user',
            name='usregion',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.usregion'),
        ),
        migrations.AddField(
            model_name='user',
            name='usstate',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.usstates'),
        ),
    ]
